<a href="https://colab.research.google.com/github/karmagurung00/Data_Analytics/blob/main/Track1/Python/Numpy_Classwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np_city=np.array(['NYC','LA','Houston','Miami','Chicago'])
np_city.ndim

1

In [ ]:
#(5,) means 4 columns and 1 row.
np_city.shape

(5,)

In [ ]:
# tells the number of elements in the array.
np_city.size

5

In [ ]:
#houston is 7 characters long which is the highest
np_city.dtype

dtype('<U7')

In [ ]:
import numpy as np

np_city_with_state=np.array([['NYC','LA','Houstons','Miami'],['NY','CA','TX','FL']])

In [ ]:
np_city_with_state.ndim

2

In [ ]:
np_city_with_state.shape

(2, 4)

In [ ]:
np_city_with_state.size

8

In [ ]:
#Longest element is 'Houstons' which is 8 characters long 
np_city_with_state.dtype

dtype('<U8')

In [ ]:
first_trial_cyclist=[10,15,17,26]
second_trial_cyclist=[12,11,21,24]

np_ftc=np.array(first_trial_cyclist)
np_stc=np.array(second_trial_cyclist)

np_ftc+np_stc

array([22, 26, 38, 50])

In [ ]:
first_trial_cyclist=[10,15,17,26]
second_trial_cyclist=[12,11,21,24]
cyclist_time=np.array([[10,15,17,26],[12,11,21,24]])
ftc_time=cyclist_time[0]            #prints everything on the first array
ftc_times=cyclist_time[0,0]         #prints the first element of the first array
stc_time=cyclist_time[1]                #prints everything on the second array
stc_times=cyclist_time[1,0]             #prints the first element of the second array
print(ftc_time)
print(ftc_times)
print(stc_time)
print(stc_times)

print( )
print(cyclist_time.ndim)


[10 15 17 26]
10
[12 11 21 24]
12

2


In [ ]:
ftc_new=cyclist_time[0,1:3]     #prints the 2nd and 3rd element of the first array
print(ftc_new)
ftc_new1=cyclist_time[1,2]    #prints the 3rd element of the second array
print(ftc_new1)
ftc_new2=cyclist_time[1,:3]    #prints all the elements from the first until the very last but doesnot include the last
print(ftc_new2)

[15 17]
21
[12 11 21]


In [ ]:
test_score=np.array([[81,71,57,63],[54,61,87,45]])
passing_score=test_score>70
passing_score
test_score[passing_score]


array([81, 71, 87])

In [ ]:
test_score=np.array([[81,71,57,63],[54,61,87,45]])
passing_score=test_score>60
print(passing_score)           #this way it only checks if the condition is true rather than printing all the scores that satisfy the condition.


[[ True  True False  True]
 [False  True  True False]]


In [ ]:
NYC_Borough=np.array(['Manhattan','Queens','Brooklyn','Staten Island','Bronx'])   #original dataset
NYC_Borough

Boroughs_NYC=NYC_Borough
Boroughs_NYC
Boroughs_in_NYC=Boroughs_NYC.view()
Boroughs_in_NYC                            #Boroughs_in_NYC is NYC_Borough

NYC_Borough is Boroughs_NYC
len(Boroughs_in_NYC)
Boroughs_in_NYC[3]

'Staten Island'

In [ ]:
NYC_Borough=np.array(['Manhattan','Queens','Brooklyn','Staten Island','Bronx'])   #original dataset
NYC_Borough

Boroughs_NYC=NYC_Borough
Boroughs_NYC

array(['Manhattan', 'Queens', 'Brooklyn', 'Staten Island', 'Bronx'],
      dtype='<U13')

In [ ]:
Boroughs_in_NYC=Boroughs_NYC.view()
Boroughs_in_NYC 

array(['Manhattan', 'Queens', 'Brooklyn', 'Staten Island', 'Bronx'],
      dtype='<U13')

In [ ]:
NYC_Borough is Boroughs_NYC
len(Boroughs_in_NYC)

5

In [ ]:
Boroughs_in_NYC[3]

'Staten Island'

In [ ]:
NYC_Borough is Boroughs_NYC

True

In [ ]:
np_sqrt=np.sqrt([2,4,9,16])
np_sqrt


from numpy import pi
np.cos(0)

1.0

In [ ]:
np.sin(pi/2)

1.0

In [ ]:
np.cos(pi)

-1.0

In [ ]:
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])


array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [ ]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [ ]:
np.floor([-1.8])

array([-2.])

In [ ]:
array_a=np.array([2,3,5,9])
array_b=np.array([0.3,0.3,0.3,0.3])

array_a*array_b        #basic multiplication of arrays

array([0.6, 0.9, 1.5, 2.7])

In [ ]:
scalar_c=0.3
array_a*scalar_c

array([0.6, 0.9, 1.5, 2.7])

In [ ]:
#TRANSPOSE
inverse_array=np.array([[10,20],[15,25]])
np.linalg.inv(inverse_array)               #linalg means linear algebra

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [ ]:
#TRACE
import numpy as np
trace_array=np.array([[10,20],[22,31]])
np.trace(trace_array)

41